### ISSUE TITLE
[dialog/notification] Improve dialog and notification styling

### ISSUE THREAD

**Issue by muwenzi** [cosmos-x/earth-ui#38]
### Tasks
   - [x] add `Accept` type for dialog
   - [x] change `warning` icon to `remove` for `Error` type dialog/notification
   - [x] change all colors of buttons according to designs

### Designs
![image](https://user-images.githubusercontent.com/12554487/50949849-cca46100-14e2-11e9-8de5-d4b4d80eebc2.png)
